### ISSUE TITLE
How to use with docker-machine?

### ISSUE THREAD

**Issue by leonelgalan** [AtomLinter/linter-codeclimate#18]
When using _docker-machine_, just like [codeclimate/codeclimate](https://github.com/codeclimate/codeclimate#prerequisites suggests), how can we run

``` sh
eval "$(docker-machine env default)"
```

Without it we get the generic

```
Error: Your Docker setup does not support the codeclimate wrapper script:

/var/run/docker.sock must exist as a Unix domain socket
...
```

Just like we would if we ran `codeclimate analyze` without configuring our shell first as instructed by _docker-machine_.

**Comment by leonelgalan** [comment]
I though I tried everything before, but simply doing the `eval` statement before opening atom through the terminal does the trick. Is this the best/only way?

``` sh
eval "$(docker-machine env default)"
atom .
```

**Comment by mrb** [comment]
@leonelgalan Sorry for the delayed response here. I personally have that line in my `.bash_profile`, which does the trick for me in general as a heavy user of docker-machine. Hope that helps.
