### ISSUE TITLE
Question: performance with some engines

### ISSUE THREAD

**Issue by rubyconvict** [AtomLinter/linter-codeclimate#24]
Hi, suppose, that I have a multi-language project (ruby + javascript) and I save some .rb file. Will the Atom plugin trigger all the enabled engines, e.g. rubocop, ESLint, like `codeclimate analyze` does or will it trigger only appropriate engine and test this file only? (I'm interested in these two engines in particular. According to comment: https://github.com/codeclimate/codeclimate/issues/62#issuecomment-142424160 this should work fine?)

**Comment by mrb** [comment]
@rubyconvict Currently the analyzer will run only on the file you have opened. Let me know if you have any other questions!
