### ISSUE TITLE
path.dirname is deprecated.

### ISSUE THREAD

**Issue by leonelgalan** [AtomLinter/linter-codeclimate#55]
Argument to `path.dirname` must be a string
```
path.dirname (/Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:9:10)
Object.<anonymous> (/Users/leonelgalan/.atom/packages/linter-codeclimate/lib/index.js:122:42)
undefined.next (null:null:null)
step (/Users/leonelgalan/.atom/packages/linter-codeclimate/lib/index.js:7:273)
```
___

_End of automated report_

How do we help? Is this going to be handled automatically once _atom-linter_ is published?

**Comment by Arcanemagus** [comment]
Fixed in v0.2.3, thanks for the report 😉.

**Comment by jaredallard** [comment]
Getting this in `0.2.5`

<img width="601" alt="screen shot 2017-12-30 at 10 12 40 pm" src="https://user-images.githubusercontent.com/2391349/34459770-94fab1f2-edae-11e7-9068-0bf3fb24af92.png">

(sorry couldn't figure out how to get the stack trace)

**Comment by Arcanemagus** [comment]
@jaredallard That's actually a separate issue. Clicking the "Report Issue" button would have started filing an issue with all the relevant information for you btw 😉.

If anyone wants to put together a PR fixing this it should be as simple as adding [these checks](https://github.com/AtomLinter/atom-linter-pug/blob/8d4f68e6d716d96d993fcb24962f75465a742b6e/lib/init.js#L128-L137) here:
https://github.com/AtomLinter/linter-codeclimate/blob/05bc926013f34341ceb8ae438f1c44b36ad3d316/lib/index.js#L132

**Comment by jaredallard** [comment]
@Arcanemagus It took me to this thread with the "Report Issue" button 🤷‍♀️
