### ISSUE TITLE
Integration fails when cli tools are out of date

### ISSUE THREAD

**Issue by olbrich** [AtomLinter/linter-codeclimate#57]
the codeclimate cli now returns a helpful message when a new version is available.  It looks like this is emitted in stderr and then combined with the json response from the engines, which breaks the JSON parsing and causes the entire thing to not work.

**Comment by maxjacobson** [comment]
Thanks for the report. I opened [a tracking issue](https://github.com/codeclimate/codeclimate/issues/609) on our CLI repo, feel free to subscribe to that issue and then upgrade your CLI after it's patched. Sorry for the inconvenience.

**Comment by olbrich** [comment]
Looks like this is fixed now.
