### ISSUE TITLE
No issues reported when `< /dev/null`  appended to the codeclimate command

### ISSUE THREAD

**Issue by cgalvarez** [AtomLinter/linter-codeclimate#59]
I get no issues reported by `linter-codeclimate` because of appending `< /dev/null` to the [command to execute](https://github.com/AtomLinter/linter-codeclimate/blob/master/lib/index.js#L156).

I've checked the issue running the package in dev mode, and executing the command printed to the Atom console in a shell terminal. I get no issues when `< /dev/null` is appended, and all existant issues appear when removed.

Example of built command reported through Atom console: `linter-codeclimate:: Command: /usr/local/bin/codeclimate analyze -f json  'style.css' < /dev/null`

Example of working command: `/usr/local/bin/codeclimate analyze -f json 'style.css'`

**Comment by Arcanemagus** [comment]
How odd, I wonder why it is trying to read in `/dev/null` 😕.

**Comment by cgalvarez** [comment]
Closing this issue since it's the same as reported issue #58
