### ISSUE TITLE
Run only on changed code

### ISSUE THREAD

**Issue by eyaleizenberg** [AtomLinter/linter-codeclimate#69]
Hi,
Is there a way to have the code climate linter run only on changed code (similar to the way it runs on the web app) rather than analyzing the whole file?

**Comment by maxjacobson** [comment]
Hi @eyaleizenberg. This isn't currently possible. It would need to be supported by [the CLI](https://github.com/codeclimate/codeclimate) before it would be supported by the Atom package. It's something we've thought about in the past, but haven't yet prioritized.

**Comment by cgalvarez** [comment]
Hi @eyaleizenberg. I think that approach would make some engines to provide false results. Think of the `duplication` engine, which could not find duplicated code inside a file if you just send the modified chunk of code, or calculating the complexity of a function with `phpmd` if you change some of its lines and only send them.

While some engines could not be affected, there are others that could, and as @maxjacobson said, this should be a feature implemented by each engine and ultimately by the CLI.
