### ISSUE TITLE
codeclimate linter does not work

### ISSUE THREAD

**Issue by olbrich** [AtomLinter/linter-codeclimate#85]
It seems to be kicking off the docker processes fine, but nothing is displayed in the UI.

**Comment by cgalvarez** [comment]
@olbrich I have PR #83 pending of @Arcanemagus' review. It should work fine for you (it fixes multiple issues). You have the installation instructions in the same thread. Plase, let me know if it works for you or you find additional issues by commenting in that same thread :wink:

**Comment by Arcanemagus** [comment]
Closing this as #83 has been merged and I'll be releasing a new version incorporating it shortly.

If you are still experiencing issues after this is released please report back or file a new issue, thanks!
